//
// pch.h
// Header for standard system include files.
//

#pragma once

#include "gtest/gtest.h"

#define KNIGHT_MAX_VELOCITY_TEST 4.8f
#define KNIGHT_MAX_HEALTH_TEST 200
#define KNIGHT_MAX_STAMINA_TEST 150
#define KNIGHT_ATTACK_SPEED_TEST 400

#define SPEARMAN_MAX_VELOCITY_TEST 4.65f
#define SPEARMAN_MAX_HEALTH_TEST 150
#define SPEARMAN_MAX_STAMINA_TEST 100
#define SPEARMAN_ATTACK_SPEED_TEST 450

#define MAGE_MAX_VELOCITY_TEST 4.5f
#define MAGE_MAX_HEALTH_TEST 100
#define MAGE_MAX_MANA_TEST 100
#define MAGE_MANA_COST_TEST 20
#define MAGE_NR_OF_SUPER_LIGHTNING_STRIKES_MIN_TEST 15
#define MAGE_NR_OF_SUPER_LIGHTNING_STRIKES_MAX_TEST 40
#define MAGE_ATTACK_SPEED_TEST 500

#define HEALTH_POTION_EFFECT_TEST 50
#define MANA_POTION_EFFECT_TEST 50
#define STAMINA_POTION_EFFECT_TEST 50
