#pragma once

enum class Textures {
  CharacterBandana,
  CharacterChainHat,
  CharacterChainHood,
  CharacterClothHood,
  CharacterGoldenHelmet,
  CharacterLeatherCap,
  CharacterMetalHelmet,
  CharacterMage,
  CharacterKnight,
  CharacterSpearman,
  CharacterArcher,
  HorizontalWall1,
  VerticalWall1,
  Bullet,
  Arrow,
  LightningStrike,
  SwordSlash,
  Tombstone,
  FloorWhole,
  FloorCracked,
  FloorSpikes,
  HealthPotion,
  ManaPotion,
  Ammo,
  SpawnPoint,
  Unknown = 99
};